let canvas = document.createElement("canvas");

canvas.id = "c";
canvas.width = "500";
canvas.height = "500";
canvas.style.display = "block";
document.body.appendChild(canvas);
let myCanvas = document.getElementById("c");
const context = canvas.getContext("2d");
context.font = "30px Arial";
context.fillText("a", 40, 200);
context.fillText("b", 180, 350);
context.fillText("c", 300, 200);
context.beginPath();
context.moveTo(100, 100);
context.lineTo(100, 300);
context.lineTo(300, 300);
context.closePath();
context.fillStyle = "red";
context.fill();
context.lineWidth = 1;
context.strokeStyle = "#666666";
context.stroke();
